### ISSUE TITLE
// TODO: deal with message size > max file bytes?

### ISSUE THREAD

**Issue by goldenMetteyya** [zowens/commitlog#1]
Hello @zowens ,

Really great project here. I have been thinking about the edge case where the message size is larger than the current space in a segment or when it may potentially cover multiple segment sizes. I do think that a message that covers multiple segments will be rare for large segments sizes like 1-4GB but for the case where the current message is greater than the space left in the open segment just opening a new one if it will fit might be a easy way to handle or we might just resize the segment to fit the data even if it is larger than default segment size. If data does cover multiple segments then the indexmetadata structure should handle this probably.   

Also it might be nice to add a segment queue for increased performance as the next segment would be ready to append to instead of having to create and open a new file.

Let me know what you think

thanks

**Comment by zowens** [comment]
Hi @goldenMetteyya,

Very good point about the message size interacting with the segment size max boundary, it is something I've at least thought about as being an issue. 

I'm thinking we'd let the segment size max slip to cover the message boundary in that case, either in the previous segment or into a fresh segment. I'm not exactly sure what Kafka does, but I'd probably end up using their semantics :)

**Comment by goldenMetteyya** [comment]
Hi @zowens ,

So from what I understood Kafka sets a message limit that can be sent to the log and the clients are responsible to portion messages larger that that limit and bookkeep this partitioning. I don't think this would work here as this is a library that is embedded in programs. I think that letting the segment resize if it passes the max size and we could maybe say if it passes above 30% of the max size we start in a new segment. 

Do you have any thoughts?

thanks

**Comment by zowens** [comment]
Hi @goldenMetteyya,

That heuristic makes sense to me. More than likely, the segment max bytes should be magnitudes higher than the message maximum. Although this brings up a good point, the lib should probably have a message limit as well.

**Comment by goldenMetteyya** [comment]
Hi @zowens ,

I think that we can add an option to LogOptions to set max message size. A new error in AppendError such as 'MessageSizeExceeded' . The 'pub fn append()'  would need a check for the 'buf' variable if it is greater than the max message size and return the 'MessageSizeExceeded' error. For the handling of the roll over if message size is greater than current size in segment should that be done from the  'pub fn append()'?

thanks
