### ISSUE TITLE
Support disabling wrapping

### ISSUE THREAD

**Issue by axos88** [zowens/commitlog#16]
Hi,

I wanted to use this as a way to store the diffs to a persistent file (a json file + modifications), to reduce I/O on an embedded system, but the fact that it can roll back and overwrite the first messages makes me unable to use it like so.

Can you support a LogOption where if the max limit is reached it will return an error rather than wrap and overwrite the first message? And in that case I would be able to truncate, compact and write the entire current state of the file as the first entry again.

**Comment by zowens** [comment]
Hi @axos88.

That sounds like a bug to me, if I'm understanding the sequence of events correctly. When you're appending to the log and the limit is reached, a new segment file should be created. The log can be read sequentially through each segment files. Do you happen to have more details on what events caused an overwrite situation?

**Comment by axos88** [comment]
Oh, I misunderstood the docs then. I did not use the crate yet, I was just exploring options. But a notification would still be necessary to know when to write the current full state and delete the old file though.
